version: '3.8'

services:
  lauapi:
    build:
      context: ./LauAPI
      dockerfile: Dockerfile
    ports:
     - "8080:8080"
     - "8081:8081"
    depends_on:
     - sqlserver
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    networks:
     - productnetwork
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Pass197004!"
      ACCEPT_EULA: "Y"
    ports:
     - "1433:1433"
    volumes:
     - sqlvolume:/var/opt/mssql
    networks:
     - productnetwork

networks:
  productnetwork:

volumes:
  sqlvolume: